myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from subapp import views



from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('subapp.urls')),
   

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

subapp/urls.py
from django.contrib import admin
from django.urls import path,include
from subapp import views


app_name = "subapp"

urlpatterns = [
    path('home/',views.home,name="home"),
    path('hi/<name>',views.hiname,name="hi"),
    path('add<a>+<b>',views.add,name="add"),
    path('temp/',views.temp_Demo,name="demo"),
    path('ghat/',views.ghat,name="ghat"),
    path('rmg/',views.rmg,name="rmg"),
    path('sarnath/',views.sarnath,name="sarnath"),
    path('temple/',views.temple,name="temple"),
    path('varansi_tourism/',views.varanasi_tour,name="varansi_tour"),
    path('hometemp/',views.hometemp,name="hometemp"),
    path('aboutus/',views.aboutus,name="aboutus"),
    path('form/',views.form,name="form")
    

]

html_app/models.py
from django.db import models

# Create your models here.

subapp/models.py
from django.db import models

# Create your models here.

html_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

subapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def index(request):
    return HttpResponse('<h1>Welcome to the project</h1>')


def home(request):
    return HttpResponse('<h1>THis iS a HoMe pag0\e</h1>')

def hiname(request,name):
    return HttpResponse('<h2>Hi {}</h2>'.format(name))

def add(request,a,b):
    return HttpResponse("<h1>THe SuM of {} anD {} iS {}</h1>".format(a,b,int(a)+int(b)))


def temp_Demo(request):
    list=['apple','mango','banana','pineapple','grapes']
    return render(request,'template1.html',context={"name":"Pranav",'list':list})
    
def ghat(request):
    return render(request,'ghat.html')

def rmg(request):
    return render(request,'rmg.html')

def sarnath(request):
    return render(request,'sarnath.html')

def temple(request):
    return render(request,'temple.html')

def varanasi_tour(request):
    return render(request,'varanasi tourism.html')


def hometemp(request):
    return render(request,'pages/home.html')

def aboutus(request):
    return render(request,'pages/about.html')

def base(request):
    return render(request,'base.html')

from django.core.files.storage import FileSystemStorage
def form(request):
    if request.method=='POST':
        fname=request.POST.get("fname")
        lname=request.POST.get("lname")
        cname=request.POST.get("cname")
        add=request.POST.get("add")
        email=request.POST.get("email")
        phone=request.POST.get("phone")
        details=request.POST.get("detials")
        acc=request.POST.get("acc")
        if request.FILES:
            files=request.FILES["profilepic"]
            fs=FileSystemStorage()
            savedfile=fs.save(files.name,files)
            file_url=fs.url(savedfile)
        
        return HttpResponse("<h1>Form Successfully Submited Data got is {} {} {} {} {} {} {} {} <img src='{}'> </h1>".format(fname,lname,cname,add,email,phone,details,acc,file_url))

    return render(request,'form.html')

templates/base.html
{% load staticfiles %}
<!Doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title%}
    <title>Bootstrap demo</title>
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'hometemp' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'aboutus' %}">About us </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>

    {% block content %}
      <h1>Base Page</h1>
    {% endblock  %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

templates/form.html
{% extends 'varanasi tourism.html' %}
{% load staticfiles %}


{% block title %}
<title>REGISTER HERE!</title>
{% endblock  %}

{% block body %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<br>
<form class="container" style="background-color:skyblue" method="POST" enctype="multipart/form-data">
    <br>
    {% csrf_token %}
    <!-- 2 column grid layout with text inputs for the first and last names -->
    <div class="row mb-4">
      <div class="col">
        <div class="form-outline">
          <input type="text" id="form6Example1" class="form-control" name="fname"/>
          <label class="form-label" for="form6Example1">First name</label>
        </div>
      </div>
      <div class="col">
        <div class="form-outline">
          <input type="text" id="form6Example2" class="form-control" name="lname"/>
          <label class="form-label" for="form6Example2">Last name</label>
        </div>
      </div>
    </div>
  
    <!-- Text input -->
    <div class="form-outline mb-4">
      <input type="text" id="form6Example3" class="form-control" name="cname"/>
      <label class="form-label" for="form6Example3">Company name</label>
    </div>
  
    <!-- Text input -->
    <div class="form-outline mb-4">
      <input type="text" id="form6Example4" class="form-control" name="add"/>
      <label class="form-label" for="form6Example4">Address</label>
    </div>
  
    <!-- Email input -->
    <div class="form-outline mb-4">
      <input type="email" id="form6Example5" class="form-control" name="email"/>
      <label class="form-label" for="form6Example5">Email</label>
    </div>
  
    <!-- Number input -->
    <div class="form-outline mb-4">
      <input type="number" id="form6Example6" class="form-control" name="phone"/>
      <label class="form-label" for="form6Example6">Phone</label>
    </div>
  
    <!-- Message input -->
    <div class="form-outline mb-4">
      <textarea class="form-control" id="form6Example7" rows="4" name="detials"></textarea>
      <label class="form-label" for="form6Example7">Additional information</label>
    </div>
    
    <div class="form-outline mb-4">
        <input type="file" class="form-control" id="form6Example7" rows="4" name="profilepic"/>
        <label class="form-label" for="form6Example7">Picture</label>
      </div>
    <!-- Checkbox -->
    <div class="form-check d-flex justify-content-center mb-4">
      <input class="form-check-input me-2" type="checkbox" value="" id="form6Example8" checked name="acc"/>
      <label class="form-check-label" for="form6Example8"> Create an account? </label>
    </div>
  
    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4">Send me the detials for Travel</button>
  </form>
  <br>
  <br>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>

{% endblock %}

templates/ghat.html
{% extends 'varanasi tourism.html' %}

<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
	<style>
		body{
			background-color: rgb(224 223 221);
		}
		.nav{
			overflow: hidden;
			background-color: #000;
		}
		.nav a{
			background-color: #000;
			text-align: center;
			display: block;
			float: left;
			text-decoration: none;
			padding: 14px 16px 14px 20px;
			color: white;
		}
		.vns {
			text-align: inherit;
			padding: 30px 160px 30px 160px;
			background-color: rgb(232 213 163);


		}
		main{
			
			padding: 10px 190px 10px 190px;
		}
		footer{
			background-color: black;
		}

		small{
			color: white;
		}
		.l{
			font-size: 1.7em;
			font-family: 'Montserrat', sans-serif;
			line-height: 2.5rem;
			color: #333;
		}
		.Quotes{
			font-size: 1.7rem;
			padding-top: 50px;
			font-family: 'Montserrat', sans-serif;
		}
		img {
  			display: block;
  			margin-left: auto;
  			margin-right: auto;
		}
		footer {
   			color: white;
   			padding: 30px 0px 30px 60px;
		}
	</style>
	<meta charset="utf-8">
	{% block title %}<title>Famous GHAT</title>{% endblock  %}
	
</head>
<body>
	<header><h1 style="font-size: 32px; text-align: center; ">VARANASI TOURISM</h1></header>
	{% block body %}

	<main>
		<div class="vns">
			<div class="ghat">
				<h1 style="text-align: center; font-size: 60px; "><b>Famous Ghat In Varanasi</b></h1>
			</div>
			<div class="l">
				<ol>
					<li>
						<strong>Dashashwamedh Ghat</strong>
						<img src="{% static 'img/vns-1.jpg' %}" width="900" height="500" style="border: 5px solid #555">
						<p>As the name suggests, it is believed that this is the place where Lord Brahma performed the Dasa Ashwamedha sacrifice. This ghat is a religious spot and many rituals are performed here.</p>
						<p>Visit at the time of Kartik Purnima to witness a celestial manifestation in the city of lights - Dev Deepavali. This Ghat is most famous for the Ganga Aarti conducted every evening, and hundreds of people visit it every day. Watching the Ganga Aarti is an experience which cannot be explained in words. When in Varanasi, make sure not to miss this calming experience.</p>
					</li>
					<li>
						<strong>Assi Ghat</strong>
						<img src="{% static 'img/vns-4.jpg' %}" width="900" height="500" style="border: 5px solid #555">
						<p>The Assi Ghat is placed at the confluence of the Rivers Assi and Ganga and is famous for the large Shiva Lingam installed under a peepal tree. It has immense religious importance and has been mentioned in the Puranas and various legends as well.</p>
						<p>Assi Ghat is the heart of Varanasi and the locals, as well as, the tourists flock there to enjoy the amazing view of the sunset and sunrise at the Ganges. It is where tourists and foreigners who travel and stay in Varanasi for a prolonged period live.  The Ghat has been a famous spot among the local youths to while away their time in the evening. Recently, the Ghat started having Aarti in the morning which is a must watch if you want to experience the true feel of Varanasi. Also, the tourists generally travel from Assi to Dashaswamedh Ghat in the evening by boat, to see the famous aarti conducted there every evening which is an experience like none other. Assi ghat is near Banaras Hindu University, and hence it is frequented by students.</p>
					</li>
					<li>
						<strong>Manikarnika Ghat</strong>
						<img src="{% static 'img/vns-8.jpg' %}" width="900" height="500" style="border: 5px solid #555">
						<p>Manikarnika Ghat is one of the holiest cremation grounds among the sacred riverfronts (ghats), alongside the river Ganga, in the city of Varanasi in the Indian state of Uttar Pradesh. In Hinduism, death is considered as a gateway to another life marked by the results of one's karma. It is believed that a dead human's soul attains moksha, and hence breaks the cycle of rebirth when cremated here.Thus, scores of the elderly across the whole country seek to walk up to its edges, and spend their last days absorbing the charisma of the ghat making death painless and insignificant to be pondered upon.</p>
						<p>The ghat is named after Sati's earrings which fell here. The Hindu genealogy registers at Varanasi are kept here.</p>
					</li>
				</ol>
		</div>
	</main>
	{% endblock %}

</body>
</html>

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>About us page</title>
{% endblock  %}

{% block content %}
<div class="container">
    <h1>About us PAGE</h1>
</div>
{% endblock  %}

templates/pages/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Home page</title>
{% endblock  %}

{% block content %}
<div class="container">
    <h1>Home PAGE</h1>
</div>
{% endblock  %}

templates/partials/_navbar.html
<header><h1 style="font-size: 32px; text-align: center; ">VARANASI TOURISM</h1></header>
<nav>
    <div class="nav">
        <a href="{% url 'subapp:varansi_tour'  %}">Home</a>
        <a href="{% url 'subapp:temple' %}">Temple</a>
        <a href="{% url 'subapp:ghat' %}">Ghat</a>
        <a href="{% url 'subapp:rmg' %}">Ramnagar Fort</a>
        <a href="{% url 'subapp:sarnath' %}">Sarnath</a>
        <a href="{% url 'subapp:form' %}">Register</a>
    </div>
</nav>

templates/sarnath.html
{% extends 'varanasi tourism.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
	<style>
		body{
			background-color: rgb(224 223 221);
		}
		.nav{
			overflow: hidden;
			background-color: #000;
		}
		.nav a{
			background-color: #000;
			text-align: center;
			display: block;
			float: left;
			text-decoration: none;
			padding: 14px 16px 14px 20px;
			color: white;
		}
		.vns {
			text-align: inherit;
			padding: 30px 160px 30px 160px;
			background-color: rgb(232 213 163);


		}
		main{
			
			padding: 10px 190px 10px 190px;
		}
		footer{
			background-color: black;
		}

		small{
			color: white;
		}
		.l{
			font-size: 1.7em;
			font-family: 'Montserrat', sans-serif;
			line-height: 2.5rem;
			color: #333;
		}
		.Quotes{
			font-size: 1.7rem;
			padding-top: 50px;
			font-family: 'Montserrat', sans-serif;
		}
		img {
  			display: block;
  			margin-left: auto;
  			margin-right: auto;
		}
		footer {
   			color: white;
   			padding: 30px 0px 30px 60px;
		}
	</style>
	<meta charset="utf-8">
	{% block title %}<title>SARNATH</title>{% endblock  %}
	
</head>
<body>
	{% block body %}
	<main>
		<div class="vns">
			<div class="sarnath">
				<h1 style="text-align: center; font-size: 60px; "><b>Sarnath</b></h1>
			</div>
			<div class="l">
				<img src="{% static 'img/vns-9.jpg' %}" width="600" height="500" style="border: 5px solid #555">
				<p>Sarnath is a place located 10 kilometres north-east of Varanasi near the confluence of the Ganges and the Varuna rivers in Uttar Pradesh, India. The Deer Park in Sarnath is where Gautama Buddha first taught the Dharma, and where the Buddhist Sangha came into existence through the enlightenment of Kondanna (Sanskrit: Kauṇḍinya).</p>
				<p>Singhpur, a village approximately one kilometre away from the site, was the birthplace of Shreyansanath, the Eleventh Tirthankara of Jainism. A temple dedicated to him is an important pilgrimage site.</p>
				<p>Also referred to as Isipatana, this city is mentioned by the Buddha as one of the four places of pilgrimage his devout followers should visit. It was also the site of the Buddha's Dhammacakkappavattana Sutta, which was his first sermon after attaining enlightenment, in which he explained the four noble truths and the teachings associated with them.</p>
				<img src="{% static 'img/vns-10.jpg' %}" width="600" height="500" style="border: 5px solid #555 ">

			</div>
		</div>
	</main>
	{% endblock %}
	
</body>
</html>

templates/template1.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="{% static 'style.css' %}"/>
</head>
<body>
<h1>My First Heading {{name}}</h1>
<p>My first paragraph.</p>
<ol>
    {% for i in list%}
    <li>{{i}}</li>
    {%endfor%}
</ol>

<h1>
    <a href="{% url 'hi' name=name %}">Templates</a>
    <img src="{% static 'car2.jpeg' %}"/>


</h1>

</body>
</html>

templates/temple.html
{% extends 'varanasi tourism.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
	<style>
		body{
			background-color: rgb(224 223 221);
		}
		.nav{
			overflow: hidden;
			background-color: #000;
		}
		.nav a{
			background-color: #000;
			text-align: center;
			display: block;
			float: left;
			text-decoration: none;
			padding: 14px 16px 14px 20px;
			color: white;
		}
		.vns {
			text-align: inherit;
			padding: 30px 160px 30px 160px;
			background-color: rgb(232 213 163);


		}
		main{
			
			padding: 10px 190px 10px 190px;
		}
		footer{
			background-color: black;
		}

		small{
			color: white;
		}
		.l{
			font-size: 1.7em;
			font-family: 'Montserrat', sans-serif;
			line-height: 2.5rem;
			color: #333;
		}
		.Quotes{
			font-size: 1.7rem;
			padding-top: 50px;
			font-family: 'Montserrat', sans-serif;
		}
		img {
  			display: block;
  			margin-left: auto;
  			margin-right: auto;
		}
		footer {
   			color: white;
   			padding: 30px 0px 30px 60px;
		}
	</style>
	<meta charset="utf-8">
	{% block title %}
	<title>FAMOUS TEMPLE</title>
	{% endblock %}
</head>
<body>
	{% block body %}
	<main>
		<div class="vns">
			<div class="temple">
				<h1 style="text-align: center; font-size: 60px; "><b>Famous Temple In Varanasi</b></h1>
			</div>
			<div class="l">
				<ol>
					<li>
						<strong>Kashi Vishwanath Temple</strong>
						<img src="{% static 'img/vns-7.jpg' %}" width="700" height="400" style="border: 5px solid #555">
						<p>Situated on the western bank of holy river Ganga in Varanasi, Kashi Vishwanath Temple is one of the 12 Jyotirlingas or temples dedicated to Lord Shiva. The main deity of Kashi Vishwanath Temple is Lord Shiva, also known as Vishwanatha or Vishweshwarar meaning 'the ruler of the universe'. The city of Varanasi, the cultural capital of India, is thus known as the city of Lord Shiva. The temple has 800 kg of gold plating on its tower.</p>
						<p>Camera, mobile phones, electronic devices are not allowed inside and must be deposited in lockers outside. Foreigners can enter from Gate number 2 where they can walk past the Indians waiting for their turn. There is also a well present within the temple complex called Jnana Vapi or wisdom well where only Hindus are allowed to enter.</p>
						<p>In the olden times, on special festivals such as Shivaratri, the king of Kashi (Kashi Naresh) visited the temple for worship during which nobody else is allowed to enter the temple premises. Devotees were allowed after the king had concluded his prayers. The importance of the Kashi Vishwanath Temple also stems from the fact that it finds mentions in several holy scriptures of the Hindus. On the outside, the temple is adorned with intricate carvings that impart a divine quality to the facade.  Other than that, the temple also houses several other small temples such as Kaalbhairav, Vishnu, Virupaksh Gauri, Vinayaka and Avimukteshwara.</p>
					</li>
					
					<li>
						<strong>New Kashi Vishwanath Temple (BHU)</strong>
						<img src="{% static 'img/vns-5.jpg' %}" width="700" height="400" style="border: 5px solid #555">
						<p>The New Vishwanath Temple is every pious man's go-to destination to feel overwhelmed by the presence and power of the great Lord Shiva. Not only is it located in the heart of the cultural capital of India - Varanasi, but its divinity is multiplied by the holy river Ganga that flows by its side. Banaras Hindu University is hence home to one of the biggest tourist attractions in the city of Varanasi, the grand New Vishwanath Temple. Visiting this temple gives the worshipper the space to put himself in the hands of God, at his disposition, and listen to the voice in his heart.</p>
						<p>The peace and calm of the temple help you forget the distractions of daily life. The positive aura in the air compels one to surrender himself in the gentle caress of the Almighty. The very famous Jyotirlinga of Shiva, Vishweshwara, is believed to have immense and unending power. A single glance of this Jyotirlinga has the ability to cleanse our soul and set us on the true path of knowledge and devotion.</p>
						<p>Although primarily a Lord Shiva temple, this beautiful temple consists of nine other temples within one and invites people of every faith to bask in its grandeur; using symbolism to express the ideas and beliefs of Hinduism. The New Vishwanath Temple incorporates every element of the Hindu cosmos- the good, the evil and the human; thus implying the major role that Dharma, Kama, Artha, Moksa and Karma play in our life.</p>
					</li>
					<li>
						<strong>Sankat Mochan Hanuman Temple</strong>
						<br>
						<img src="{% static 'img/vns-6.jpg' %}" width="600" height="700" style="border: 5px solid #555">
						<p>The Sankat Mochan Hanuman Temple is situated by the River Assi and was built in the 1900s by the freedom fighter Pandit Madan Mohan Malviya. It is dedicated to Lord Rama and Hanuman.</p>
						<p>Varanasi is always related to Sankat Mochan Temple and is an essential part of this holy city. Every person visiting Varanasi visits this temple and pay their respects to Hanuman. The laddoo offered at this temple is essentially famous among the locals.While visiting Sankat Mochan be aware of the monkeys who throng the temple premises and tend to steal away the prasad. However, they are totally harmless if you let them be on their own.</p>
					</li>
				</ol>
				
			</div>
		</div>
	</main>
	{% endblock %}
	
</body>
</html>

templates/varanasi tourism.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
	<style>
		body{
			background-color: rgb(224 223 221);
		}
		.nav{
			overflow: hidden;
			background-color: #000;
		}
		.nav a{
			background-color: #000;
			text-align: center;
			display: block;
			float: left;
			text-decoration: none;
			padding: 14px 16px 14px 20px;
			color: white;
		}
		.vns {
			text-align: inherit;
			padding: 30px 160px 30px 160px;
			background-color: rgb(232 213 163);


		}
		main{
			
			padding: 10px 190px 10px 190px;
		}
		footer{
			background-color: black;
			color: white;
   			padding: 30px 0px 30px 60px;
		}

		small{
			color: white;
		}
		.l{
			font-size: 1.7em;
			font-family: 'Montserrat', sans-serif;
			line-height: 2.5rem;
			color: #333;
		}
		.Quotes{
			font-size: 1.7rem;
			padding-top: 50px;
			font-family: 'Montserrat', sans-serif;
		}
	</style>
	<meta charset="utf-8">
	{% block title %}
	<title>WELCOME TO VARANASI TOURISM</title>
	{% endblock  %}
	
</head>
<body>
	
	{% include 'partials/_navbar.html' %}

	{% block body %}
	<main>
		<div class="vns">
			<div class="img">
					<img src="{% static 'img/vns-3.jpg' %}" width="900" height="500" style="border: 5px solid #555">
			</div>
			<div class="Quotes">
		 		<b><i><q>The Spiritual Capital of India</q></i></b>
			</div>
			<div class="l">
				<h3>Varanasi Tourism</h3>
				<p>World's oldest living city, Varanasi - also known as Kashi (City of Life) and Benaras, is the spiritual capital of India. It is one of Hinduism's seven holy cities. The old city of Varanasi lies along the western banks of the Ganges, spread across a labyrinth of narrow galis. Be prepared to walk on foot and encounter some holy cows! Temples at almost every turn engulf Varanasi but the <a href="temple.html" style="text-decoration: none; color: blue;">Kashi Vishwanath Temple</a> is the most visited and the oldest of the lot. Benaras is known as the city of Lord Shiva for a reason, and rightfully so.</p>
				<p>Varanasi is considered an auspicious place to die, as it is believed to grant moksha or liberation from the cycle of life and death. Spiritually enlightening, the heart of the city pulsates around the ghats, about 80 of which border the Ganges. Be prepared for the sights, sounds and smells! Don't miss out on the hot chaat and cool lassi. Though, all chaos and noise on the ghats take a pause before dusk when the Ganga Aarti begins to take place, a ceremony of immense grandeur.</p>
				<p>This divine city is also an important destination for Buddhists. Gautam Buddha preached his first sermon in Benaras, a part which is now in 
					<a href="sarnath.html" style="text-decoration: none; color: blue;">Sarnath.</a></p>
			</div>
		</div>
	</main>
	{% endblock %}
	<footer>
		<small style="text-align: left;">&copy; VARANASI TOURISM 2022. ALL RIGHTS ARE RESERVED</small>
		<a href="{% url 'subapp:varansi_tour'  %}" style="text-decoration: none; color: white; padding: 30px 30px 30px 890px; "><b>Home</b></a>
	</footer>
	
	
</body>
</html>